@startuml
skinparam linetype ortho
(*) --> ===BEGIN=== 
===BEGIN=== -->"Search"
===BEGIN===  --> "Send Number"
"Send Number" --> "Save To Disk"

"Search" --> "Look at Disk"
"Search" --> "Look at Memory"
"Look at Disk" --> ===MERGE===
"Look at Memory" --> ===MERGE===
===MERGE=== --> "Results"
 "TT" --> (*)

@enduml